# -*- coding: utf-8 -*-
"""
Created on Sun Feb 28 14:41:20 2021

@author: noahs
"""

#ALL PATHS ARE RELATIVE TO MUSICSAMPLER PATH ENIVRONMENT VARIABLE
#This means a paths of "" will be the MusicSampler environment variable directory

from os.path import join
from os import getenv, walk
from .sampler import loadSmp
smpPath = getenv("MUSICSAMPLER")


#Recursively shows all PickledMusicSamplers and descriptions relative to MUSICSAMPLER PATH
#For each PickledMusicSampler shows all pieces
def tree(path=""):
    directory = join(smpPath,path)
    for (dirpath, _, filenames) in walk(directory):
        for file in filenames:
            if ".smp" in file:
                info(join(dirpath, file))
    
    
 
#Provides information about a Sampler and the music that it has generated
def info(path):
    smp = loadSmp(path)
    print("\n")
    print("Path: "+ path)
    print("Music Description: " + smp.description)
    print("Piece Titles: ")
    for i,piece in enumerate(smp.generated):
        print("   Piece "+ str(i)+": " + piece.title)
    
#plays music generated by smpfile
def play(path):
    pass


#Allows you to explore different PickledMusicSamplers that you have created
#And listen to music generated by repective network
def explore(path):
    pass
    